server.port: 8082
spring:
  application:
    name: checkout-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKEN:localhost}
          transaction:
            producer:
              configuration:
                retries: 3
                max.in.flight.requests.per.connection: 1
                acks: 'all'
                linger.ms: 50
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        orderChannel:
          destination: ORDER_TOPIC
        paymentChannel:
          destination: PAYMENT_TOPIC
        approvePaymentForOrder:
          destination: ORDER_PAYMENT_TOPIC
        sendOrderEmailIn:
          destination: EMAIL_SENDER_TOPIC
        sendOrderEmailOut:
          destination: EMAIL_SENDER_TOPIC
