server.port: 8999
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:4200
      routes:
        - id: store-service
          uri: http://localhost:8081
          predicates:
            - Path=/store/**
#            - After
#          - Before=2017-09-11T17:42:47.789-07:00[America/Alaska]
#            - Host=http://localhost
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-CUSTOM-RESPONSE,HELLO
        - id: checkout-service
          uri: http://localhost:8082
          predicates:
            - Path=/checkout/**
          filters:
            - StripPrefix=1
